### ISSUE TITLE
About the results

### ISSUE THREAD

**Issue by chenhaocs** [hikvision-research/ProbabilisticTeacher#2]
Hi, thanks for sharing the codes. Will you update the links of weights and log files in the "Main Results" ?

**Comment by merlinarer** [comment]
> Hi, thanks for sharing the codes. Will you update the links of weights and log files in the "Main Results" ?

Yes, c2f is already there, and others may take a while. Several emails sent to me says the results are reproduced with this code, and you can run it following the instruction.

**Comment by chenhaocs** [comment]
https://github.com/hikvision-research/ProbabilisticTeacher/blob/ea34bca288f4609c1882439540cfda5de4bf2ce5/pt/modeling/roi_heads/fast_rcnn.py#L250

Another question, there's some difference about the formular between the code and the paper, could you explain the reason ?

**Comment by merlinarer** [comment]
> https://github.com/hikvision-research/ProbabilisticTeacher/blob/ea34bca288f4609c1882439540cfda5de4bf2ce5/pt/modeling/roi_heads/fast_rcnn.py#L250
> 
> Another question, there's some difference about the formular between the code and the paper, could you explain the reason ?

Here is the KL-divergence,  equal to the CE during optimization.

**Comment by kinredon** [comment]
When to release the weights. and log files for other adaptation scenarios? @merlinarer
