### ISSUE TITLE
Issues about Data Preparation

### ISSUE THREAD

**Issue by Shengcao-Cao** [hikvision-research/ProbabilisticTeacher#6]
Thanks for your great work and sharing the code!

I'm trying to reproduce your results on Cityscapes to FoggyCityscapes. However, I find the data preparation description is not very clear on this dataset:

- If I do not modify Detectron2 code, it will by default read images with `.jpg` suffix. However, the images from Cityscapes are in `.png` format.
- In Detectron2's evaluation code (https://github.com/facebookresearch/detectron2/blob/v0.5/detectron2/evaluation/pascal_voc_evaluation.py#L132), it reads `pose` `truncate` `difficult` properties which are not actually produced by your annotation transformation script.
- Besides, the data folder structure is not very clear from the description and code. It would really take some time to understand how to unzip the Cityscapes files and move things around so that they can match your scripts.

Would you mind giving more complete instructions on data preparation?

**Comment by merlinarer** [comment]
I would like to clarify your questions on data preparation details.
- Detectron2 reads images with `.jpg` by default, and you are supposed to transform images in Cityscapes to `.png`  format or change `jpeg_file = os.path.join(dirname, "JPEGImages", fileid + ".jpg")` to `jpeg_file = os.path.join(dirname, "JPEGImages", fileid + ".png")` in [this line](https://github.com/facebookresearch/detectron2/blob/c54429b60a64736c8b62002c5729eb818835f745/detectron2/data/datasets/pascal_voc.py#L42).
- PASCAL VOC xml contains `pose truncate difficult` properties by default, and you are supposed to comment them out [this](https://github.com/facebookresearch/detectron2/blob/c54429b60a64736c8b62002c5729eb818835f745/detectron2/evaluation/pascal_voc_evaluation.py#L141) in Detectron2 or add dummy properties when annotation transformation.
- We just follow the default data folder structure of PASCAL VOC, and you can adapt our scripts (especiallly Cityscapes path) to fit your envienments. We will update more straightforward scripts for a better understanding.

**Comment by Shengcao-Cao** [comment]
Thanks for your helpful response!
